#!/bin/bash

function MkIni {
  mkdir -p /tmp/cdm-$3

  (
    echo "experiment         = \"experiment-12.10.2025\""
    echo "agent              = \"cdm-$3\""
    echo "work_folder        = \"/tmp/cdm-$3\""
    echo "latex              = \"test\""
    echo ""
    echo "[ftp]"
    echo "user               = \"modelling_bus\""
    echo "password           = \"Geheim1967\""
    echo "port               = 21"
    echo "server             = \"$2\""
    echo "single_server_mode = $4"
    echo "active_transfers   = $5"
    echo "prefix             = \"modelling_bus\""
    echo ""
    echo "[mqtt]"
    echo "user               = \"modelling_bus\""
    echo "password           = \"Geheim1967\""
    echo "port               = 1883"
    echo "broker             = \"$2\""
    echo "prefix             = \"modelling_bus\""
    echo "load_delay         = 10"
  ) > $1.ini
}

MkIni mobile                    localhost               tester false false
MkIni home                      frame.fritz.box         tester false false
MkIni tuwien                    dm-lab.big.tuwien.ac.at tester false true

MkIni ../model_listener/mobile  localhost               listener false false

MkIni ../model_listener/home1   frame.fritz.box         home-1 false false
MkIni ../model_listener/home2   frame.fritz.box         home-2 false false
MkIni ../model_listener/home3   frame.fritz.box         home-3 false false

MkIni ../model_listener/tuwien1 dm-lab.big.tuwien.ac.at tuwien-1 false true
MkIni ../model_listener/tuwien2 dm-lab.big.tuwien.ac.at tuwien-2 false true
MkIni ../model_listener/tuwien3 dm-lab.big.tuwien.ac.at tuwien-3 false true
